providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[phases.test]
cmds = ["yarn test"]

[start]
cmd = "./start.sh"
