AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Parameters:
  serverUrl:
    Description: "Klutch Server URL"
    Type: String
  miniappId:
    Description: "Miniapp Id"
    Type: String
  privateKey:
    Description: "Miniapp Private Key"
    Type: String

Resources:
  ServerlessFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ../dist/
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 10
      Environment:
        Variables:
          SERVER_URL: !Ref serverUrl
          MINIAPP_ID: !Ref miniappId
          PRIVATE_KEY: !Ref privateKey
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: "rate(1 day)"
